### ISSUE TITLE
Need to add Deploy status badge in README.md

### ISSUE THREAD

**Issue by raghunath-r-a** [LoginRadius/engineering-portal#766]
Please add the Deploy status badge in README.md

Status badges are visual representations of your site's status, served as image files you can add to repository READMEs, documentation, or any other web page. Please follow this [URL](https://docs.netlify.com/monitor-sites/status-badges/#add-status-badges)

**Comment by Pradumn-18** [comment]
I suppose there are some inconsistency with the deployment command. Because the npm i command throws error.

**Comment by abhir9** [comment]
@Pradumn-18 could you share a screenshot.

**Comment by Pradumn-18** [comment]
Yeah sure, I am attaching the log file of Netlify deployment build for better insights. The package installation is fine now. I figured that the package installation works fine with lower NodeJs version like 14.x, 12.x but gives error on 16.x. Now I face error in "npm run develop" command mentioned in README.md of the repository.

Please take a deep look into it.

[Log_File.txt](https://github.com/LoginRadius/engineering-portal/files/7244656/Log_File.txt)

**Comment by AmreshSinha** [comment]
Builds are passing on travis-ci

**Comment by AmreshSinha** [comment]
Tried on Travis-CI
Build is succeeding on Node v14.18.0 but failing on v16.10.0

**Comment by AmreshSinha** [comment]
@raghunath-r-a @abhir9 you can assign me this issue. Just specify the final testing platform. I prefer going with Travis or as @Pradumn-18 said Netflify.

**Comment by Pradumn-18** [comment]
@AmreshSinha I guess Travis CI will not be preferable because their you would not be able to deploy the site. It will start executing the build but at last this is basically a site to be hosted, which will keep running in your build if it passes.I myself tried same on Github Action which is equivalent to Travis CI.

Moreover could you please share the logs of build that you claim is passing.

**Comment by AmreshSinha** [comment]
> @AmreshSinha I guess Travis CI will not be preferable because their you would not be able to deploy the site. It will start executing the build but at last this is basically a site to be hosted, which will keep running in your build if it passes.I myself tried same on Github Action which is equivalent to Travis CI.
> 
> Moreover could you please share the logs of build that you claim is passing.

@Pradumn-18 
Yeah it will be purely used for testing purposes and not for actual production build purpose.

and the fail error log:
https://api.travis-ci.com/v3/job/540618696/log.txt

**Comment by Pradumn-18** [comment]
@AmreshSinha Yes I agree to that, it fails with node version 16.x as I have also pointed out same in my prior comment.

**Comment by raghunath-r-a** [comment]
@AmreshSinha @Pradumn-18 Thanks for highlighting this issue. Project maintainers are trying to fix this on priority. 

Meanwhile, adding a status badge in RADME.md has been addressed by another pull request. (For your reference).

CC: @abhir9 @mohammed786 @pareek-narendra

**Comment by mohammed786** [comment]
@Pradumn-18 Seems like gatsby version used in this portal is 2.x.x, which is not supported in node v16.x, kindly raise the PR in support to node version either `v14.x` or `v12.x` to run it locally till we upgrade the gatsby version for this portal.

For more details checkout this issue #789

**Comment by Pradumn-18** [comment]
Though the PR seems to have merged but unfortunately I am still not able to the badge for Netlify deployment. 

Could you please look into that.

**Comment by Pradumn-18** [comment]
@mohammed786 Sure would do that.

**Comment by dontech09** [comment]
Wish to work on that

**Comment by raghunath-r-a** [comment]
@dontech09 Thanks for your interest in fixing this. But this has been already addressed by this pull request: https://github.com/LoginRadius/engineering-portal/pull/792
